version: '3'
services:
  website:
    image: flashspys/nginx-static
    container_name: metronome
    networks:
      - traefik
    ports:
      - 8083:80
    volumes:
      - ./build:/static
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
